### ISSUE TITLE
Invalid GPS coordinates on GoPro 6 - coords completely off track

### ISSUE THREAD

**Issue by highsource** [JuanIrache/gopro-utils#3] opened 2018-10-07 12:43 UTC
Please see #2 for the background information.

A further problem I'm facing are coordinate which are completely off track.

BIN file:

[GX010039.bin.zip](https://github.com/JuanIrache/gopro-utils/files/2453909/GX010039.bin.zip)

This is the GPX track I'm getting:

[GX010039.gpx.zip](https://github.com/JuanIrache/gopro-utils/files/2453910/GX010039.gpx.zip)

The tracks looks "exploded" in a few places:

![qgis-1](https://user-images.githubusercontent.com/6707996/46581829-fe6adf00-ca3e-11e8-81ed-e18a4bf474e7.PNG)

This part here is completely off the track. Quite sure I did not drive there:

![qgis-4](https://user-images.githubusercontent.com/6707996/46581833-04f95680-ca3f-11e8-8721-e83287459320.PNG)

Same here:

![qgis-3](https://user-images.githubusercontent.com/6707996/46581835-0aef3780-ca3f-11e8-8479-2ecdeb7eacd0.PNG)

Check the "vertical" part here in the middle. Looks quite consistent. Except there's no road there and I did not drive there. Also consider the part in the upper right corner.

I also get severely inprecise coordinates along the track:

![qgis-2](https://user-images.githubusercontent.com/6707996/46581844-4427a780-ca3f-11e8-954a-70c9110c64bf.PNG)

Quik shows a somewhat better looking track:

![quik](https://user-images.githubusercontent.com/6707996/46581853-4984f200-ca3f-11e8-935d-2d67d0fbaf49.PNG)

However Quik does not show almost the half of the drack I actually drove.

I don't think these "explosions" of the track can't be explained by the imprecision of GPS. Ok, I'm fine with a few meters, but I see jumps of several hundreds meters if not kilometers here. Also, this is not visible in Quik.

**Comment by JuanIrache** [comment] 2018-10-08 10:15
Duplicate of #2

**Closed by JuanIrache** 2018-10-08 10:15 UTC
