### ISSUE TITLE
Number of rows and Timestamp/Miliseconds data different in Json vs CSV files 

### ISSUE THREAD

**Issue by EdgarRomeroC** [JuanIrache/gopro-utils#1] opened 2018-10-06 18:09 UTC
Used the utilities as indicated. 
When running the code using multiple samples, in this case several 1min GoPro Hero 5 Black MP4s,
I noticed that the JSON document has always less rows and different elapsed time in milliseconds (difference of Value.utc between rows) than the data contained in GPS.CSV file.

Is there a reason for that?, since the expected difference is supposed to be  only format. 

Also, it is clear that the sampling rate might not always be 55 milliseconds, it could be 52, or something else; however, the difference in the specific time and the amount on data is puzzling.

**Comment by JuanIrache** [comment] 2018-10-07 12:38
Hi @EdgarRomeroC ,

I will have to look into that when I have more spare time. From what I remember the milliseconds of the CSV are just deduced by assuming each telemetry package lasts 1 second, but the number of samples varies slightly from package to package, so their duration is adjusted proportionally. That was enough for my needs back when I created this. I think I need to update it to use the actual time stamps of each package, but I need to look into it.

Thanks

**Comment by JuanIrache** [comment] 2018-10-07 13:29
Ok, it turns out I had broken the TS field from the original repository. That's where the UTC timecode should go. It should be back now. If the data there is more consistent than my deduced milliseconds column, I will adapt it, and add this fix to the other CSV files. Does that make sense?

**Comment by EdgarRomeroC** [comment] 2018-10-09 15:55
Yes. Definitively is much better to use the camera’s time stamp.. sampling rate might not be absolutely even but is better to understand the actual time of an event. People can resample or interpolate their data if needed. Thanks a lot for your contribution .

-------
One side question: So far I’ve not managed to get the elevation data to make sense; in my case I was using data from a car race, and the elevation show all sorts of negative values (-10ft , -11ft) and suddenly changes to (+40ft, +45ft).. and I don’t know why… I used the Quik app gauges, and it shows the same as the data, meaning is consistent. Now I’m wondering if something is wrong with the camera… Based on your experience, have you had any similar behavior?

Thanks again,
Edgar Romero

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JuanIrache** [comment] 2018-10-09 16:00
The origin of the problem is that I was working with the Hero5 Session, which does not have a GPS antenna and its metadata has no timestamps (which come from the GPS). That's why the milliseconds value is there, so that we can somewhat sync data with video later. I will update that column to match the timecode, at least in the GPS csv.

**Comment by JuanIrache** [comment] 2018-10-10 09:36
Should be fixed with a4a04a6c2b1d6f5d0b31f52c8601c5427254c04e

**Closed** 2018-10-10 09:36 UTC
